/**
 * Copyright (C) 2014 Thiago Moreira (tmoreira2020@gmail.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package br.com.thiagomoreira.liferay.plugins.notfound.services.model.impl;

import br.com.thiagomoreira.liferay.plugins.notfound.services.model.NotFound;
import br.com.thiagomoreira.liferay.plugins.notfound.services.service.NotFoundLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the NotFound service. Represents a row in the &quot;TM_NF_NotFound&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link NotFoundImpl}.
 * </p>
 *
 * @author Thiago Moreira
 * @see NotFoundImpl
 * @see br.com.thiagomoreira.liferay.plugins.notfound.services.model.NotFound
 * @generated
 */
public abstract class NotFoundBaseImpl extends NotFoundModelImpl
    implements NotFound {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a not found model instance should use the {@link NotFound} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            NotFoundLocalServiceUtil.addNotFound(this);
        } else {
            NotFoundLocalServiceUtil.updateNotFound(this);
        }
    }
}
